apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.trading/client-id: 09236ff7-533c-4cc8-ade1-783f1f127728
  labels:
    azure.workload.trading/use: "true"